export const SUBJECTS = [
    "Afrikaans First Language",
    "Afrikaans Second Language",
    "English First Language",
    "English Second Language",
    "isiNdebele First Language",
    "isiNdebele Second Language",
    "isiXhosa First Language",
    "isiXhosa Second Language",
    "isiZulu First Language",
    "isiZulu Second Language",
    "Sepedi First Language",
    "Sepedi Second Language",
    "Sesotho First Language",
    "Sesotho Second Language",
    "Setswana First Language",
    "Setswana Second Language",
    "siSwati First Language",
    "siSwati Second Language",
    "Tshivenda First Language",
    "Tshivenda Second Language",
    "Xitsonga First Language",
    "Xitsonga Second Language",
    "Mathematics",
    "Biology",
    "Physical Science",
    "Physiology",
    "Arabic",
    "Classical Greek",
    "French",
    "German First Language",
    "German Third Language",
    "Gujarati",
    "Hebrew",
    "Hindi",
    "isiNdebele Third Language",
    "isiXhosa Third Language",
    "isiZulu Third Language",
    "Italian",
    "Latin",
    "Portuguese",
    "Sepedi Third Language",
    "Sesotho Third Language",
    "Setswana Third Language",
    "siSwati Third Language",
    "Spanish",
    "Tamil",
    "Telugu",
    "Tshivenda Third Language",
    "Urdu",
    "Xitsonga Third Language",
    "Biblical Studies",
    "Economics",
    "Geography",
    "History",
    "Jewish Studies",
    "Accounting",
    "Additional Mathematics",
    "Afrikaanse Letterkunde",
    "Agricultural Economics",
    "Agricultural Science",
    "Anatomy and Music",
    "Animal Husbandry",
    "Applied Agricultural Science",
    "Art",
    "Bookbinding",
    "Bricklaying and Plastering",
    "Building Construction",
    "Building Construction Theory",
    "Business Economics",
    "Commercial Mathematics",
    "Computer Studies",
    "Computyping",
    "Cookery and Nutrition",
    "Dance",
    "Dance Performance",
    "Design",
    "Electricians’ Work",
    "Electronics",
    "English Literature",
    "Equine Studies",
    "Farm Mechanics",
    "Field Husbandry",
    "Fitting and Turning",
    "Functional Mathematics",
    "Functional Physical Science",
    "Graphic Art"
]